### ISSUE TITLE
Mirror Augment

### ISSUE THREAD

**Issue by DarkFaded** [lucidrains/stylegan2-pytorch#205]
First of all, thanks for you work!

Does this have a mirror augment already? Or is it beneficial to feed the GAN with mirrored images yourself?

Secondly. I am a little confused about the D and G loss that you see in the console. What kind of D and G (or GP) values are you looking for? Small numbers? Big numbers? Negative numbers?

**Comment by lucidrains** [comment]
@DarkFaded Hi! I would say, in the advent of the new type of differentiable augmentation (used with `--aug-prob`), horizontal flip dataset augmentation is no longer useful! So don't worry too much about that!

D and G are hard to interpret, due to the adversarial nature of GANs, but usually you would like both to be non-zero and below 10. GP should always be close to 0 with occasional spikes.

**Comment by lucidrains** [comment]
If you ever see D and G suddenly shoot upwards to the 100s, then the game is over and you will pick the generator just before 'divergence'

**Comment by DarkFaded** [comment]
Thank you very much for your answers, looking forward to creating awesome things with your GAN!
